import { BadRequestException, Injectable } from '@nestjs/common';
import { UrlService } from '../url/url.service';

@Injectable()
export class WordsService {
  constructor(private readonly urlService: UrlService) {}
  colors: string[] = [
    'alloy',
    'amber',
    'aqua',
    'azure',
    'apple',
    'bark',
    'beige',
    'black',
    'blue',
    'bone',
    'brass',
    'brown',
    'chart',
    'clay',
    'coal',
    'coral',
    'cream',
    'crimson',
    'cyan',
    'fawn',
    'fern',
    'flesh',
    'fire',
    'fog',
    'fusch',
    'gains',
    'glow',
    'gold',
    'gray',
    'green',
    'hazel',
    'honey',
    'hazel',
    'honey',
    'india',
    'indigo',
    'iris',
    'ivory',
    'jade',
    'jazz',
    'khaki',
    'lapis',
    'lavender',
    'lake',
    'lemon',
    'lilac',
    'lime',
    'linen',
    'maize',
    'mauve',
    'melon',
    'minty',
    'moss',
    'navy',
    'neon',
    'olive',
    'onyx',
    'orange',
    'palm',
    'parch',
    'peach',
    'pear',
    'peony',
    'pink',
    'plum',
    'purple',
    'quilt',
    'rose',
    'ruby',
    'rust',
    'rust',
    'ruby',
    'ruby',
    'salmon',
    'saff',
    'sepia',
    'sienna',
    'silver',
    'smoky',
    'snow',
    'steel',
    'tawny',
    'teal',
    'taupe',
    'tease',
    'tiger',
    'umber',
    'venus',
    'violet',
    'vivid',
    'wheat',
    'white',
    'yellow',
    'zinc',
  ];
  animals: string[] = [
    'ant',
    'ape',
    'bat',
    'bee',
    'cat',
    'cod',
    'cow',
    'crab',
    'deer',
    'dog',
    'dove',
    'duck',
    'eel',
    'elk',
    'finch',
    'fox',
    'frog',
    'gecko',
    'gnu',
    'goat',
    'hamster',
    'hare',
    'hawk',
    'hen',
    'hog',
    'hyena',
    'ibex',
    'jackal',
    'jaguar',
    'jay',
    'kiwi',
    'koi',
    'koala',
    'lamb',
    'lemur',
    'leopard',
    'lion',
    'llama',
    'mantis',
    'marmot',
    'mole',
    'moose',
    'mouse',
    'newt',
    'ocelot',
    'orca',
    'otter',
    'owl',
    'panda',
    'parrot',
    'pig',
    'puma',
    'quail',
    'quokka',
    'rabbit',
    'raccoon',
    'ram',
    'rat',
    'seal',
    'shark',
    'sheep',
    'skunk',
    'slug',
    'sloth',
    'snail',
    'snipe',
    'stork',
    'stoat',
    'swan',
    'swift',
    'tarsier',
    'tiger',
    'toad',
    'toucan',
    'tuna',
    'turkey',
    'viper',
    'vole',
    'walrus',
    'wasp',
    'weasel',
    'whale',
    'wolf',
    'wombat',
    'x-ray_fish',
    'xenops',
    'yak',
    'zebra',
    'zorse',
  ];

  private randomElement(array: string[]): string {
    const randomIndex = Math.floor(Math.random() * array.length);
    return array[randomIndex];
  }
  async alreadyExist(randomUrl: string): Promise<boolean> {
    try {
      const shortUrl = await this.urlService.getByShortUrl(randomUrl);
      return shortUrl ? true : false;
    } catch (error) {
      throw new BadRequestException(`ERROR:${error}`);
    }
  }

  async getRandomUrl(): Promise<string> {
    const color: string = this.randomElement(this.colors);
    const animal: string = this.randomElement(this.animals);
    let randomUrl = `/${color}-${animal}`;

    while (await this.alreadyExist(randomUrl)) {
      randomUrl = `/${color}-${animal}-${Math.floor(Math.random() * 1000)}`;
    }
    return randomUrl;
  }
}
